fixtures:
  symlinks:
    ssh: "#{source_dir}"
  repositories:
    concat: https://github.com/puppetlabs/puppetlabs-concat.git
    sshkeys:
      repo: https://github.com/puppetlabs/puppetlabs-sshkeys_core.git
      puppet_version: '>= 6.0'
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
